###################################################################

# Created by write_sdc on Mon May  4 11:25:22 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current uA
set_driving_cell -lib_cell INVX1 [get_ports clka]
set_driving_cell -lib_cell INVX1 [get_ports clkb]
set_driving_cell -lib_cell INVX1 [get_ports global_reset]
set_driving_cell -lib_cell INVX1 [get_ports player_left_input]
set_driving_cell -lib_cell INVX1 [get_ports player_right_input]
set_driving_cell -lib_cell INVX1 [get_ports player_shoot_input]
set_driving_cell -lib_cell INVX1 [get_ports player_display]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_x[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_x[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_x[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_x[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_y[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_y[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_y[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {player_coordinate_y[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaders_display[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaders_display[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_x[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_x[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_x[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_x[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_y[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_y[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_y[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader1_coordinate_y[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_x[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_x[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_x[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_x[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_y[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_y[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_y[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invader2_coordinate_y[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_x[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_x[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_x[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_x[0]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_y[3]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_y[2]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_y[1]}]
set_driving_cell -lib_cell INVX1 [get_ports {invaderbullet_coord_y[0]}]
set_driving_cell -lib_cell INVX1 [get_ports                                    \
invaderbullet_player_collision_signal]
set_driving_cell -lib_cell INVX1 [get_ports                                    \
invaderbullet_shield_collision_signal]
set_driving_cell -lib_cell INVX1 [get_ports invader_outofbounds_signal_1]
set_driving_cell -lib_cell INVX1 [get_ports invader_outofbounds_signal_2]
create_clock [get_ports clka]  -period 20  -waveform {0 10}
set_input_delay -clock clka  1  [get_ports clkb]
set_input_delay -clock clka  1  [get_ports global_reset]
set_input_delay -clock clka  1  [get_ports player_left_input]
set_input_delay -clock clka  1  [get_ports player_right_input]
set_input_delay -clock clka  1  [get_ports player_shoot_input]
set_input_delay -clock clka  1  [get_ports player_display]
set_input_delay -clock clka  1  [get_ports {player_coordinate_x[3]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_x[2]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_x[1]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_x[0]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_y[3]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_y[2]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_y[1]}]
set_input_delay -clock clka  1  [get_ports {player_coordinate_y[0]}]
set_input_delay -clock clka  1  [get_ports {invaders_display[1]}]
set_input_delay -clock clka  1  [get_ports {invaders_display[0]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_x[3]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_x[2]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_x[1]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_x[0]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_y[3]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_y[2]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_y[1]}]
set_input_delay -clock clka  1  [get_ports {invader1_coordinate_y[0]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_x[3]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_x[2]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_x[1]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_x[0]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_y[3]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_y[2]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_y[1]}]
set_input_delay -clock clka  1  [get_ports {invader2_coordinate_y[0]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_x[3]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_x[2]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_x[1]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_x[0]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_y[3]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_y[2]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_y[1]}]
set_input_delay -clock clka  1  [get_ports {invaderbullet_coord_y[0]}]
set_input_delay -clock clka  1  [get_ports invaderbullet_player_collision_signal]
set_input_delay -clock clka  1  [get_ports invaderbullet_shield_collision_signal]
set_input_delay -clock clka  1  [get_ports invader_outofbounds_signal_1]
set_input_delay -clock clka  1  [get_ports invader_outofbounds_signal_2]
set_output_delay -clock clka  1  [get_ports player_left_motion]
set_output_delay -clock clka  1  [get_ports player_right_motion]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_x[3]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_x[2]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_x[1]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_x[0]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_y[3]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_y[2]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_y[1]}]
set_output_delay -clock clka  1  [get_ports {closest_invader_coord_y[0]}]
set_output_delay -clock clka  1  [get_ports play]
set_output_delay -clock clka  1  [get_ports reset]
set_output_delay -clock clka  1  [get_ports invader_direction]
set_output_delay -clock clka  1  [get_ports playerbullet_fire]
set_output_delay -clock clka  1  [get_ports invaderbullet_fire]
set_output_delay -clock clka  1  [get_ports move_down]
set_output_delay -clock clka  1  [get_ports {state[1]}]
set_output_delay -clock clka  1  [get_ports {state[0]}]
